# Generated by Django 6.0.7 on 2026-07-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_hours', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('drive_hours', models.FloatField()),
                ('eta', models.CharField(max_length=50)),
                ('eta_date', models.CharField(max_length=50)),
                ('stops_data', models.JSONField()),
                ('logs_data', models.JSONField()),
                ('route_geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
