# Generated by Django 6.0.7 on 2026-07-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('driver_id', models.CharField(max_length=100, unique=True)),
                ('truck_number', models.CharField(blank=True, max_length=100)),
                ('co_driver', models.CharField(blank=True, max_length=255)),
                ('carrier_id', models.CharField(blank=True, max_length=255)),
                ('main_office', models.CharField(blank=True, max_length=255)),
                ('used_cycle_hours', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='tripdispatch',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdispatch',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
        ),
    ]
