# Generated by Django 5.2.3 on 2026-07-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_driver_id_alter_tripdispatch_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdispatch',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
